// Generated by CoffeeScript 1.6.3
(function() {
  var Image, path;

  Image = require('../lib/image');

  path = './test/images/global';

  module.exports = {
    testImageDimensions: function(beforeExit, assert) {
      var image;
      image = new Image('100x300.png', path);
      return image.readDimensions(function() {
        assert.equal(100, image.width);
        assert.equal(300, image.height);
        return assert.equal("4a930265ea1cab7bc075cece7aa24e27", image.checksum);
      });
    }
  };

}).call(this);
