// Generated by CoffeeScript 1.6.3
(function() {
  var HorizontalMapper, Image, Sprite, VerticalMapper, mapper, path;

  Sprite = require('../lib/sprite');

  Image = require('../lib/image');

  VerticalMapper = require('../lib/mapper').VerticalMapper;

  HorizontalMapper = require('../lib/mapper').HorizontalMapper;

  path = './test/images';

  mapper = new VerticalMapper(10);

  module.exports = {
    testSpriteLoading: function(beforeExit, assert) {
      var sprite;
      sprite = new Sprite('global', path, mapper);
      return sprite.load(function() {
        return assert.equal(2, sprite.images.length);
      });
    },
    testWritingOutput: function(beforeExit, assert) {
      var sprite;
      sprite = new Sprite('global', path, mapper);
      return sprite.load(function() {
        return sprite.write(function() {
          return assert.ok(true);
        });
      });
    },
    testImageInfo: function(beforeExit, assert) {
      var sprite;
      sprite = new Sprite('global', path, mapper);
      return sprite.load(function() {
        assert.equal(100, sprite.image('100x300').width);
        assert.equal(300, sprite.image('100x300').height);
        assert.equal(0, sprite.image('200x200').positionX);
        assert.equal(310, sprite.image('200x200').positionY);
        return assert.isUndefined(sprite.image('350x151'));
      });
    },
    testImageChecksums: function(beforeExit, assert) {
      var sprite;
      sprite = new Sprite('global', path, mapper);
      return sprite.load(function() {
        return assert.equal(32, sprite.checksum().length);
      });
    }
  };

}).call(this);
