// Generated by CoffeeScript 1.6.3
(function() {
  var sprite;

  sprite = require('../');

  sprite.sprite('global', {
    path: './images',
    padding: 2
  }, function(err, s) {
    var i;
    console.log("created sprite from " + s.images.length + " images");
    i = s.image('50 100');
    return console.log("image '50 100' with dimensions " + i.width + "x" + i.height + " is at position " + i.positionX + "," + i.positionY);
  });

}).call(this);
