// Generated by CoffeeScript 1.6.3
(function() {
  var node, sprite, str, stylus;

  stylus = require('stylus');

  node = stylus.nodes;

  sprite = require('../');

  str = require('fs').readFileSync(__dirname + '/sprite.styl', 'utf8');

  /*
  stylus(str)
    .set('filename', __dirname + '/sprite.styl')
    .define('sprite', sprite.stylus())
    .render (err, css) ->
      console.log err, css
  */


  sprite.stylus({
    path: "./images",
    watch: true
  }, function(err, helper) {
    var output;
    output = function() {
      return stylus(str).set('filename', __dirname + '/sprite.styl').define('sprite', helper.fn).render(function(err, css) {
        if (err) {
          console.log(err);
        }
        return console.log(css);
      });
    };
    output();
    helper.on("update", output);
    return console.log("watching for file changes in './images' ...");
  });

}).call(this);
