// Generated by CoffeeScript 1.6.3
(function() {
  var Image, checksum, im;

  im = require("imagemagick");

  checksum = require("./checksum");

  Image = (function() {
    Image.prototype.positionX = null;

    Image.prototype.positionY = null;

    Image.prototype.width = null;

    Image.prototype.height = null;

    Image.prototype.checksum = null;

    function Image(filename, path) {
      this.filename = filename;
      this.path = path;
      this.name = this.filename.replace(/\.(png|gif|jpg|jpeg)$/, '');
    }

    Image.prototype.readDimensions = function(cb) {
      var _this = this;
      return checksum.file(this.file(), function(err, sum) {
        return im.identify(_this.file(), function(err, img) {
          if (!err) {
            _this.width = img.width;
            _this.height = img.height;
            _this.checksum = sum;
          }
          return cb(err);
        });
      });
    };

    Image.prototype.file = function() {
      return "" + this.path + "/" + this.filename;
    };

    return Image;

  })();

  module.exports = Image;

}).call(this);
