// Generated by CoffeeScript 1.6.3
(function() {
  var HorizontalMapper, Mapper, VerticalMapper, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Mapper = (function() {
    Mapper.prototype.height = 0;

    Mapper.prototype.width = 0;

    function Mapper(padding) {
      this.padding = padding;
    }

    Mapper.prototype.area = function() {
      return this.width * this.height;
    };

    return Mapper;

  })();

  VerticalMapper = (function(_super) {
    __extends(VerticalMapper, _super);

    function VerticalMapper() {
      _ref = VerticalMapper.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    VerticalMapper.prototype.map = function(images) {
      var image, _i, _len;
      this.width = this.height = 0;
      for (_i = 0, _len = images.length; _i < _len; _i++) {
        image = images[_i];
        image.positionX = 0;
        image.positionY = this.height;
        this.height += image.height + this.padding;
        if (image.width > this.width) {
          this.width = image.width;
        }
      }
      return this.height -= this.padding;
    };

    return VerticalMapper;

  })(Mapper);

  HorizontalMapper = (function(_super) {
    __extends(HorizontalMapper, _super);

    function HorizontalMapper() {
      _ref1 = HorizontalMapper.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    HorizontalMapper.prototype.map = function(images) {
      var image, _i, _len;
      this.width = this.height = 0;
      for (_i = 0, _len = images.length; _i < _len; _i++) {
        image = images[_i];
        image.positionX = this.width;
        image.positionY = 0;
        this.width += image.width + this.padding;
        if (image.height > this.height) {
          this.height = image.height;
        }
      }
      return this.width -= this.padding;
    };

    return HorizontalMapper;

  })(Mapper);

  module.exports.VerticalMapper = VerticalMapper;

  module.exports.HorizontalMapper = HorizontalMapper;

}).call(this);
